image: python:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: http://docker:2375

before_script:
  - pip install pipenv

build:
   stage: build
   script: python -m pipenv run pyb package

test:
   stage: test
   script: python -m pipenv run pyb verify
