image: docker

services:
  - docker:dind

#variables:
#   PIP_DEFAULT_TIMEOUT=100

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - echo $CI_REGISTRY_IMAGE
  - echo $CI_COMMIT_REF_SLUG

build:
   stage: build
   script:
    - docker build --pull --rm=false -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

test:
   stage: test
   script: docker run -e DOCKER_PORT=$DOCKER_PORT "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" make test
