image: python:3.6

services:
  - docker:dind

variables:
  DOCKER_HOST: http://docker:2375

before_script:
  - pip install pipenv

build:
   stage: build
   script: bin/make.py package

test:
   stage: test
   script: bin/make.py verify

cache:
  paths:
    - $HOME/.local/share/virtualenvs/
    - /root/.local/share/virtualenvs/
